workspace(name = "learn_bazel")

load("@bazel_tools//tools/jdk:local_jdk.bzl", "local_jdk")

local_jdk(
    name = "local_jdk",
    jdk_home = "%JAVA_HOME%",
)

register_toolchains("@local_jdk//:all")
